# Generated by Django 4.2 on 2023-05-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='client',
            name='film',
        ),
        migrations.RemoveField(
            model_name='director',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='film',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_studio', to='film_rent.studio'),
        ),
        migrations.AddField(
            model_name='client',
            name='clients_films',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients_films', to='film_rent.film'),
        ),
        migrations.AddField(
            model_name='director',
            name='directors_actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='directors_actors', to='film_rent.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_actor', to='film_rent.actor'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to='film_rent.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='film_rent.order'),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_studio', to='film_rent.studio'),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_film', to='film_rent.film'),
        ),
    ]
