# Generated by Django 4.2 on 2023-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0002_remove_actor_studio_remove_client_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clients_films',
            field=models.ManyToManyField(blank=True, null=True, to='film_rent.film'),
        ),
        migrations.AlterField(
            model_name='director',
            name='directors_actors',
            field=models.ManyToManyField(blank=True, null=True, to='film_rent.actor'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
