# Generated by Django 4.2 on 2023-05-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0003_alter_client_clients_films_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=255, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Рік зйомки'),
        ),
    ]
