# Generated by Django 4.2 on 2023-05-11 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0004_alter_film_options_alter_film_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'Актори'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Режисери'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name_plural': 'Прокати'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name_plural': 'Студії'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_studio', to='film_rent.studio', verbose_name='Студія'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я актора"),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище актора'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='num_of_movies',
            field=models.IntegerField(verbose_name='Кількість зйомок'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clients_films',
            field=models.ManyToManyField(blank=True, null=True, to='film_rent.film', verbose_name='Фільми'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я клієнта"),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Прізвище клієнта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rentals_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість прокатів'),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='director',
            name='directors_actors',
            field=models.ManyToManyField(blank=True, null=True, to='film_rent.actor', verbose_name='Актор'),
        ),
        migrations.AlterField(
            model_name='director',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='director',
            name='film_company',
            field=models.CharField(max_length=100, verbose_name='Кінокомпанія'),
        ),
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Ім’я режисера'),
        ),
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище режисера'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_actor', to='film_rent.actor', verbose_name='Актор'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата закінчення прокату'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='film_name',
            field=models.CharField(max_length=255, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна прокату'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_studio', to='film_rent.studio', verbose_name='Студія'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='returns',
            field=models.IntegerField(default=0, verbose_name='Кількість повернень'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата початку прокату'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='founded_year',
            field=models.PositiveIntegerField(verbose_name='Рік заснування'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='number_of_films',
            field=models.PositiveIntegerField(verbose_name='Кількість знятих фільмів'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибуток'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_film', to='film_rent.film', verbose_name='Фільм'),
        ),
    ]
