# Generated by Django 4.2 on 2023-05-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0005_alter_actor_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Платежі'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to='film_rent.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Дата замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateField(verbose_name='Дата повернення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.IntegerField(verbose_name='Об’єм замовлення'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Борг'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='film_rent.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_terms',
            field=models.CharField(max_length=50, verbose_name='Умови оплати'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Готівка'), ('CARD', 'Кредитна картка'), ('BANK_TRANSFER', 'Банківський переказ')], max_length=20, verbose_name='Тип платежу'),
        ),
    ]
