# Generated by Django 4.2 on 2023-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0006_alter_order_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Прибуток'),
        ),
    ]
