# Generated by Django 4.2 on 2023-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rent', '0007_alter_studio_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='genre',
            field=models.CharField(default=None, max_length=255, verbose_name='Жанр'),
        ),
    ]
